import { query } from "@/lib/db";
import { treatments as defaults, type Treatment } from "@/data/site";
export const cmsDefaults:Record<string,string>={
  "home.eyebrow":"Personalised skin & wellness · Leeds","home.title":"Your Skin. Your Confidence. Your Glow.","home.intro":"Professional, personalised treatments in a calm one-to-one setting — created around your skin goals, comfort and confidence.","home.offer":"","home.hero_image":"",
  "about.image_url":"","about.title":"Meet the person behind your treatment.","about.text":"Luminous is designed around attentive one-to-one care, clear explanations and a comfortable treatment journey.","about.practitioner":"Luminous Skin Clinic Practitioner","about.qualifications":"",
  "contact.location":"Leeds, United Kingdom","contact.email":"","contact.phone":"","contact.whatsapp":"","contact.map_url":"",
  "booking.deposit_policy":"Deposit rules vary by treatment.","booking.cancellation_policy":"Please contact the clinic in advance to cancel or reschedule.","booking.notice_hours":"24",
  "global.instagram":"","global.facebook":"","global.tiktok":"","global.announcement":""
};
export async function ensureCms(){await query(`CREATE TABLE IF NOT EXISTS site_content(content_key TEXT PRIMARY KEY,content_value TEXT NOT NULL DEFAULT '',group_name TEXT NOT NULL DEFAULT 'general',updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS cms_faqs(id BIGSERIAL PRIMARY KEY,question TEXT NOT NULL,answer TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT true);CREATE TABLE IF NOT EXISTS result_media(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,treatment_name TEXT,before_image TEXT,after_image TEXT,description TEXT,is_published BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS promo_codes(id BIGSERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,discount_type TEXT NOT NULL DEFAULT 'percent',discount_value NUMERIC NOT NULL DEFAULT 0,starts_at TIMESTAMPTZ,ends_at TIMESTAMPTZ,is_active BOOLEAN NOT NULL DEFAULT true);CREATE TABLE IF NOT EXISTS waitlist(id BIGSERIAL PRIMARY KEY,customer_name TEXT NOT NULL,email TEXT,phone TEXT,treatment_name TEXT,preferred_date DATE,status TEXT NOT NULL DEFAULT 'waiting',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);for(const[k,v]of Object.entries(cmsDefaults)){await query(`INSERT INTO site_content(content_key,content_value,group_name) VALUES($1,$2,$3) ON CONFLICT(content_key) DO NOTHING`,[k,v,k.split('.')[0]])}}
export async function getCms(){try{await ensureCms();const r=await query<{content_key:string;content_value:string}>("SELECT content_key,content_value FROM site_content");return {...cmsDefaults,...Object.fromEntries(r.rows.map(x=>[x.content_key,x.content_value]))}}catch{return cmsDefaults}}
export async function getTreatments():Promise<Treatment[]>{try{const r=await query<Record<string,unknown>>("SELECT name,slug,category,price,deposit,duration_minutes,short_description,description,benefits,suitable_for,aftercare,image_url,is_active FROM treatments WHERE is_active=true ORDER BY name");if(!r.rows.length)return defaults;return r.rows.map(row=>{const d=defaults.find(x=>x.slug===row.slug)??defaults[0];return{...d,name:String(row.name),slug:String(row.slug),category:String(row.category||d.category),price:Number(row.price),duration:Number(row.duration_minutes),short:String(row.short_description||d.short),description:String(row.description||d.description),benefits:String(row.benefits||'').split('\\n').filter(Boolean).length?String(row.benefits).split('\\n').filter(Boolean):d.benefits,suitableFor:String(row.suitable_for||'').split('\\n').filter(Boolean).length?String(row.suitable_for).split('\\n').filter(Boolean):d.suitableFor,aftercare:String(row.aftercare||'').split('\\n').filter(Boolean).length?String(row.aftercare).split('\\n').filter(Boolean):d.aftercare,fallbackImage:String(row.image_url||d.fallbackImage)}})}catch{return defaults}}
export async function getReviews(){try{const r=await query<Record<string,unknown>>("SELECT client_name,treatment_name,rating,review_text FROM reviews WHERE is_approved=true ORDER BY created_at DESC");return r.rows}catch{return[]}}
export async function getFaqs(){try{await ensureCms();const r=await query<Record<string,unknown>>("SELECT id,question,answer FROM cms_faqs WHERE is_active=true ORDER BY sort_order,id");return r.rows}catch{return[]}}
export async function getResults(){try{await ensureCms();const r=await query<Record<string,unknown>>("SELECT * FROM result_media WHERE is_published=true ORDER BY created_at DESC");return r.rows}catch{return[]}}
